export const MODULES = {
  dashboard: true,
  dashboardCliente: true,
  clientes: true,
  documentacion: false,
  sucursal: false,
  bitacora: false,
  tickets: true,
  proyectos: false,
  vehiculos: false,
  opciones: true,
  perfil: true,
  adminUsuarios: true,
  adminTiposEquipos: false,
  reportes: false,
};
